"""
PRODUCT:
  get_product()
  list_products()
  create_product()
  update_product()
  activate_product()         
  deactivate_product()         

STOCK:
  reserve_stock()             
  release_reservation()       
  fulfill_reservation()       
  create_stock_movement()
  list_stock_movements()    
  get_available_stock()       
  update_reserved_quantity()
  check_stock_availability()   
"""
